export const HOME_ROUTE = '/'
export const AUTH_ROUTE = '/authenticate'
export const PRICING_ROUTE = '/pricing'
export const FEATURES_ROUTE = '/features'
export const DASHBOARD_ROUTE = '/dashboard'
export const JOBS_ROUTE = '/jobs'
export const JOB_VIEW_ROUTE = '/jobs/:id'