"""add job id to deals

Revision ID: 3e4fda763fcd
Revises: daf4469ba870
Create Date: 2026-05-29 11:06:23.468394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4fda763fcd'
down_revision: Union[str, Sequence[str], None] = 'daf4469ba870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deals_job_id'), 'deals', ['job_id'], unique=False)
    op.create_foreign_key(None, 'deals', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_index(op.f('ix_deals_job_id'), table_name='deals')
    op.drop_column('deals', 'job_id')
    # ### end Alembic commands ###
